# RetailPulse_AI_Analytics

# Dataset Overview

The Online Retail II dataset contains transactional sales records from a UK-based online retail company between December 2009 and December 2011.

The company primarily sells unique gift products, and many customers are wholesalers. The dataset includes customer purchases, product details, transaction timestamps, quantities, pricing information, and customer geographic information.

This dataset is highly suitable for retail analytics because it enables the analysis of customer purchasing behavior, sales trends, product demand, and customer value patterns.

The primary business problems addressed using this dataset include:

- Understanding customer purchasing behavior
- Identifying high-value and loyal customers
- Forecasting future sales demand
- Detecting customer churn risk
- Optimizing inventory management
- Improving business decision-making through data-driven insights

# Problem-Solving
The Quantity feature helps analyze product demand patterns and supports inventory optimization and demand forecasting.

# Data Collection:
The dataset has been referred from: 
https://www.kaggle.com/datasets/lakshmi25npathi/online-retail-dataset

| Column      | Description                    | Business Use                               |
| ----------- | ------------------------------ | ------------------------------------------ |
| Invoice     | Unique transaction/bill number | Identify and group customer transactions   |
| StockCode   | Unique product identifier      | Product-level sales analysis               |
| Description | Product name/details           | Product insights and demand analysis       |
| Quantity    | Number of units purchased      | Demand forecasting and inventory analysis  |
| InvoiceDate | Transaction date and time      | Time-series analysis and sales forecasting |
| Price       | Price per product unit         | Revenue and pricing analysis               |
| Customer ID | Unique customer identifier     | Customer segmentation and churn analysis   |
| Country     | Customer geographic location   | Regional and market analysis               |

In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
file_path = ("../data/rawdata/online_retail_II.xlsx")

xls = pd.ExcelFile(file_path)

df_2009 = pd.read_excel(xls, sheet_name="Year 2009-2010")
df_2010 = pd.read_excel(xls, sheet_name="Year 2010-2011")

df = pd.concat([df_2009, df_2010], ignore_index=True)

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.shape

(1067371, 8)

In [5]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [8]:
df = df.dropna(subset=['Customer ID'])

In [9]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [10]:
df.shape

(824364, 8)

In [11]:
df[df['Invoice'].astype(str).str.startswith('C')].shape

(18744, 8)

In [12]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

In [13]:
df[df['Quantity'] <= 0].shape

(0, 8)

In [14]:
df = df[df['Quantity'] > 0]

In [15]:
df[df['Price'] <= 0].shape

(71, 8)

In [16]:
df = df[df['Price'] > 0]

In [17]:
df.duplicated().sum()

26124

In [18]:
df = df.drop_duplicates()

In [19]:
# Remove non-product administrative records

exclude_keywords = [
    "Manual",
    "POSTAGE",
    "BANK CHARGES",
    "ADJUST"
]

df = df[~df["Description"].isin(exclude_keywords)]

In [20]:
df['Revenue'] = df['Quantity'] * df['Price']

In [21]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day
df['Hour'] = df['InvoiceDate'].dt.hour
df['Weekday'] = df['InvoiceDate'].dt.day_name()

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 776941 entries, 0 to 1067369
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      776941 non-null  object
 1   StockCode    776941 non-null  object
 2   Description  776941 non-null  object
 3   Quantity     776941 non-null  int64
 4   InvoiceDate  776941 non-null  datetime64[ns]
 5   Price        776941 non-null  float64
 6   Customer ID  776941 non-null  float64
 7   Country      776941 non-null  object
 8   Revenue      776941 non-null  float64
 9   Year         776941 non-null  int32
 10  Month        776941 non-null  int32
 11  Day          776941 non-null  int32
 12  Hour         776941 non-null  int32
 13  Weekday      776941 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(4), int64(1), object(5)
memory usage: 77.1+ MB

In [23]:
df.shape

(776941, 14)

In [24]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day,Hour,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1,7,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1,7,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1,7,Tuesday

In [25]:
df.to_csv("../data/processed/cleaned_retail_data.csv", index=False)

In [26]:
df = pd.read_csv("../data/processed/cleaned_retail_data.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day,Hour,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1,7,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1,7,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1,7,Tuesday

In [27]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day,Hour,Weekday
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1,7,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,7,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1,7,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1,7,Tuesday

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776941 entries, 0 to 776940
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      776941 non-null  int64
 1   StockCode    776941 non-null  object
 2   Description  776941 non-null  object
 3   Quantity     776941 non-null  int64
 4   InvoiceDate  776941 non-null  datetime64[ns]
 5   Price        776941 non-null  float64
 6   Customer ID  776941 non-null  float64
 7   Country      776941 non-null  object
 8   Revenue      776941 non-null  float64
 9   Year         776941 non-null  int64
 10  Month        776941 non-null  int64
 11  Day          776941 non-null  int64
 12  Hour         776941 non-null  int64
 13  Weekday      776941 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(6), object(4)
memory usage: 83.0+ MB